site_name: Introduction to containers
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Course material:
      - Introduction to containers: course_material/introduction_containers.md
      - Managing containers and images: course_material/managing_docker.md
      - Working with dockerfiles: course_material/dockerfiles.md
      - Running containers with singularity: course_material/singularity.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  icon:
    repo: fontawesome/brands/github

# Repository
repo_name: sib-swiss/containers-introduction-training
repo_url: https://github.com/sib-swiss/containers-introduction-training
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
